### ISSUE TITLE
Permission denied error after updating to 0.24.4/0.24.5

### ISSUE THREAD

**Issue by csmith** [supabase/storage-api#224]
# Bug report

## Describe the bug

After updating from 0.24.3 to 0.24.5, the following error occurs when starting the storage container:

```
2022-11-19T14:45:13: PM2 log: PM2 successfully stopped
2022-11-19T14:45:14: PM2 log: Launching in no daemon mode
2022-11-19T14:45:14: PM2 log: App [server:0] starting in -fork mode-
2022-11-19T14:45:14: PM2 log: App [server:0] online
running migrations
finished migrations
error: permission denied for database postgres
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/app/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 99,
  severity: 'ERROR',
  code: '42501',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'aclchk.c',
  line: '3447',
  routine: 'aclcheck_error'
}
```

After a lot of debugging, I think this is because 0.24.4 started using pg-boss, and pg-boss is attempting to run its own migrations which include a `CREATE SCHEMA IF NOT EXISTS pgboss` and the postgres account storage runs under (rightfully) doesn't have permission to make new schemas.

Also, curiously, the process seems to keep running but never starts to listen for incoming connections. I'd expect it to exit after the migration failed.

## To Reproduce

1. Use the standard supabase docker-compose file from https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml
2. Bump the version of the storage-api to 0.24.5 (or 0.24.4)
3. See error

## Expected behavior

1) If an error occurs, the process exits or handles it in some way other than becoming hung
2) The service doesn't try to create new, undocumented schemas :)

**Comment by csmith** [comment]
Also, the error message is super unhelpful - it doesn't provide any context to what was going on at the time, but I guess that might be an upstream issue with pg-boss more than anything else?

**Comment by fenos** [comment]
Hello, @csmith  thanks for reporting the issue, 
I haven't considered the fact that the DB user might not have the right to create the pg-boss schema

I will do the following to address this:

- Add pg-boss queue worker under a feature flag, so you can enable or keep it disabled if not necessary
- Add an environment variable for a specific connection string to pg-boss, this way you can create another user with permission and let it run

**Comment by fenos** [comment]
Awesome! closing this
